### ISSUE TITLE
Cannot get prediction model running

### ISSUE THREAD

**Issue by Jerzeek** [Jerzeek/PlasticScanner#1]
In the folder failed_attempt, I tried to use a TensorFlow model to predict what plastic the scanned values were. 
It uses all the code from [ReReMeter repository](https://github.com/arminstr/reremeter/tree/master/software ) (totally cool guys!) I tore out the FireBase parts and replaced it with a CSV import.

I was able to train the model and save it as a file in the dnn_estimator folder (I think, it ran for a while and saved some files)

But now if I want to use the model and make a prediction it says: 
`Function call stack:
pruned`

I'm sure the sensor values reach untill `imported.signatures["predict"]` (which is a valid attribute of the model)

I am using TensorFlow 2.3.1

**Comment by Jerzeek** [comment]
`Function call stack: pruned` was not so useful, maybe here a bit more output:

` PS D:\NextCloud\Projects\Plastic Sense\Building\tf_test> & C:/Users/devos/AppData/Local/Programs/Python/Python38/python.exe "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py"
2020-12-15 11:29:11.389210: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-12-15 11:29:11.422234: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-12-15 11:29:22.719100: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-12-15 11:29:23.957230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: Quadro K620M computeCapability: 5.0
coreClock: 1.124GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 14.92GiB/s
2020-12-15 11:29:24.253686: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-12-15 11:29:24.401715: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-12-15 11:29:24.568453: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-12-15 11:29:24.784836: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-12-15 11:29:25.069148: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-12-15 11:29:25.221076: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-12-15 11:29:25.617296: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-12-15 11:29:25.821072: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-12-15 11:29:26.311622: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-15 11:29:26.952226: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2bb1a413860 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-15 11:29:27.248050: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-15 11:29:27.270225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-15 11:29:27.549166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
-----------------------------------------------------------------
[ 2.69610000e+04  4.65812000e+05  7.44313000e+05  3.41199000e+05
  4.23140000e+05  3.20050000e+05  3.87348000e+05  1.76584000e+05
  3.09445556e+03 -1.55043846e+03  8.19410000e+02 -6.87266667e+02
  6.72980000e+02 -2.10764000e+03]
tf.Tensor(
[ 2.6961000e+04  4.6581200e+05  7.4431300e+05  3.4119900e+05
  4.2314000e+05  3.2005000e+05  3.8734800e+05  1.7658400e+05
  3.0944556e+03 -1.5504385e+03  8.1940997e+02 -6.8726666e+02
  6.7297998e+02 -2.1076399e+03], shape=(14,), dtype=float32)
Traceback (most recent call last):
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 147, in <module>
    detectAndUpload()
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 130, in detectAndUpload
    data = convertPredictionToPlasticType(predict(wavelengths))
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 42, in predict
    return imported.signatures["predict"](
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1655, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 246, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1673, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  3.0944556e+03 -1.5504385e+03  8.1940997e+02 -6.8726666e+02
  6.7297998e+02 -2.1076399e+03], shape=(14,), dtype=float32)
Traceback (most recent call last):
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 147, in <module>
    detectAndUpload()
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 130, in detectAndUpload
    data = convertPredictionToPlasticType(predict(wavelengths))
  File "d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py", line 42, in predict
    return imported.signatures["predict"](
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1655, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 246, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1673, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1722, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\devos\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  ConcatOp : Expected concatenating dimensions in the range [0, 0), but got -1
         [[node dnn/input_from_feature_columns/input_layer/concat (defined at d:/NextCloud/Projects/Plastic Sense/Building/tf_test/tfpredictionInterface.py:21) ]] [Op:__inference_pruned_692]

Function call stack:
pruned `
